services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api/v1
      - NODE_ENV=development
    stdin_open: true
    tty: true
    networks:
      - inventory-network

networks:
  inventory-network:
    external: true
